# Generated by Django 3.0.8 on 2020-07-27 11:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streaming_app', '0002_auto_20200727_1106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Room',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='body',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='title',
            new_name='name',
        ),
    ]
