# Generated by Django 3.0.8 on 2020-07-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_app', '0003_auto_20200727_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='author',
            new_name='admin',
        ),
    ]
